name: Deploy

on:
  push:
    branches: [ "GitHubActions" ]
  
jobs:
  deploy:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: docker build -f GitHubActions/Dockerfile -t imran-patwa/githubactions GitHubActions
    - run: echo "sasdadasd_adss_sdfsf_dfsgag_sdafgfddsaf" | docker login -u imran-patwa --password-stdin
    - run: docker push imran-patwa/githubactions:latest
