# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "SingletonDemo" ] 

jobs:
  build:

    runs-on: [self-hosted]

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x   
    - name: Restore
      run: dotnet restore SingletonDemo/SingletonDemo.sln
    - name: Build 
      run: dotnet build SingletonDemo/SingletonDemo.sln --no-restore
    - name: Test 
      run: dotnet test SingletonDemo/SingletonDemo.sln --no-build --verbosity normal
    - name: Publish Application
      run: |
        dotnet publish SingletonDemo/SingletonDemo.sln `
          --configuration Release `
          --output D:\GitHubActions\Publish\SingletonDemo
    - name: Stop IIS Website
      shell: powershell
      run: |
          Import-Module WebAdministration
          Stop-Website -Name "SingletonDemo"

    # Optional: Stop App Pool
    - name: Stop IIS App Pool
      shell: powershell
      run: |
          Import-Module WebAdministration
          Stop-WebAppPool -Name "SingletonDemoAppPool"

    - name: Copy Files to IIS Folder
      shell: powershell
      run: |
          $source = "D:\GitHubActions\Publish\SingletonDemo\*"
          $destination = "C:\inetpub\wwwroot\SingletonDemo"

          if (!(Test-Path $destination)) {
              New-Item -ItemType Directory -Path $destination -Force
          }

          Copy-Item $source `
                    -Destination $destination `
                    -Recurse `
                    -Force

     # Optional: Start App Pool
    - name: Start IIS App Pool
      shell: powershell
      run: |
          Import-Module WebAdministration
          Start-WebAppPool -Name "SingletonDemoAppPool"

    - name: Start IIS Website
      shell: powershell
      run: |
          Import-Module WebAdministration
          Start-Website -Name "SingletonDemo"
